### PR TITLE
Vaadin 24 upgrade

### PR DESCRIPTION
**Pull request by samie**
Vaadin 24 is often incompatible with Vaadin 14 and does not compile with the same setup. I made the required changes to the project and updated both the add-on and tests. 

It might be worth forking the current Vaadin  14 version in main to its own branch before considering these changes.

### CODE REVIEW

**Comment by Sergio70** [comment]
Hello.
It's been a long time since the last update of this project.
you can use your own fork to make modifications, maintain it and upload your versions to the vaadin directory.
Unfortunately I cannot follow up on this project.
Greetings.

**Comment by samie** [comment]
Sure, I understand. There still seems to be users  asking for upgrade, so wanted to address those. Instead of publishing a new add-on, how do you feel if we move the Directory ownership of the current add-on to @parttio who can then do the releases? We have done that with other similar add-ons already. You can also join the organization in GitHub, if you feel like it.

**Comment by Sergio70** [comment]
Yes it seems correct to me.
If there is anything you need to make this change, let me know.

**Comment by Sergio70** [comment]
Sure, I already made the transfer.

**Comment by samie** [comment]
There is now released version for Vaadin 24+ at https://vaadin.com/directory/component/ace-widget1/2.0.0

**Pull request merged**
