### PR TITLE
WIP: setHeight, setWidth and setSizeFull

### PR DESCRIPTION
**Pull request by EricFranke**
Hi,

this feature is nearly complete. For some reason, the height of the editor is always 210 px. Setting the width works just fine. Do you have an idea?

### CODE REVIEW

**Comment by Sergio70** [comment]
I was parsing it but couldn't solve this so I didn't implement HasSize and just add editor.getElement (). GetStyle (). Set ("min-height", height); I know it's not the right thing to do, but it was a quick alternative to the rudimentary height setting the solution is in.

**Comment by EricFranke** [comment]
editor.getElement().getStyle().set("min-height", height) throws a NPE, because the editor object is not initialized. This solution did not work for me, that's why I am currently trying to implement it.

**Comment by EricFranke** [comment]
I found the problem. In ace-widget.js is the asynchronous method "connectedCallback". This method calls "initializeEditor", which calls "injectStyle". This method sets editor.style.height. Since this is computed asynchronously, setting the height of the editor dom element after initializing the java object does nothing, because the setting will be overriden.

**Comment by Sergio70** [comment]
True, I just checked it, you can only change the height after it starts, for example with one click DOM event or DOM event focus etc.
I made the update to the vaadin directory with the modifications you made.

**Comment by mheicke** [comment]
hey, great work :) any chance you merge the PR soon and release it to Vaadin directory? The workaround with editor.getElement().getStyle().set ("min-height", height) seems not to work for me and it would be helpful to set the width to 100% since we show it in a dialogue

**Pull request closed without merging**
