### PR TITLE
Added more methods + MAJOR Bugfix

### PR DESCRIPTION
**Pull request by F0rce**
While merging in the AceEditor.java file the package at the top has been removed. So if you would release a new version, it would NOT work. I fixed it in this pull request.

Added more methods:
- setShowPrintMargin
- setShowInvisibles
- setShowGutter
- setHighlightActiveLine

Adjusted view test view file and changed version.

### CODE REVIEW

**Comment by F0rce** [comment]
#5 could be closed if approved

**Comment by Sergio70** [comment]
Hello, I am going to carry out tests to validate it and perform the update, I will tell you that in the setHeight and setWidth methods they are configured in such a way that they can adapt as much as possible to our needs in the sizes this due to problems in the initialization, I do not know you can correctly adjust the height and width.

image

**Comment by F0rce** [comment]
As far as I tested, Setting the height and width works better then setting the min/max values. Thanks for the fast answer. 

Very appreciated,
David

**Comment by F0rce** [comment]
This commit also includes the max-width / max-height "solution" I talked about earlier

**Comment by desertfox94** [comment]
I think the problem of setting the **height** is an internal problem of the ace-widget. The height is calculated on the fly according to the number of lines within the editor. The css height property will always be overwritten by the ace-editor.

**Comment by desertfox94** [comment]
Is it possible to separate the re-adding of the package from the adding of new features?
It would be awesome if separate fix version would be available in the Vaadin Repository soon :)

**Comment by F0rce** [comment]
@desertfox94 I don't think it is. @Sergio70 doesn't has too much time to work on this. So I think the easiest way for him, is to "merge everything". But I really hope, the changes will be soon in the Vaadin Repo.

**Review by Sergio70 — APPROVED** [review]

**Review by Sergio70 — APPROVED** [review]

**Review by Sergio70 — APPROVED** [review]

**Review by Sergio70 — APPROVED** [review]

**Review by Sergio70 — APPROVED** [review]

**Review by Sergio70 — APPROVED** [review]

**Review by Sergio70 — APPROVED** [review]

**Review by Sergio70 — APPROVED** [review]

**Review by Sergio70 — APPROVED** [review]

**Review by Sergio70 — APPROVED** [review]

**Review by Sergio70 — APPROVED** [review]

**Pull request merged**
